project_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-5Qgs4qOsPgbXnTtlFjeTTo-ln8885t0'
project_name: 'ABI Deepwatch MDR'
project_code: 'bffb7631-0830-42a1-8d12-82482b5ffca6'
project_type: 'ABI CloudFormation Project Type'
partner_name: 'DeepWatch'
launch_date: '2023-10-04'
repo_name: 'cfn-abi-deepwatch-mdr'
templates_info:
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-5Qgs4qOsPgbXnTtlFjeTTo-ln8886kt'
    file_name: 'templates/deepwatch-root-stack.yaml'
    count_flag: 'true'
  - template_id: 'abp-1kirFQBF75MfEQ3RbMQHRb-5Qgs4qOsPgbXnTtlFjeTTo-ln8887cq'
    file_name: 'templates/deepwatch-logging-resource-configuration.yaml'
    count_flag: 'false'
