project:
  name: cfn-abi-deepwatch-mdr
  owner: zachary.wallace@deepwatch.com
  package_lambda: false
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
  - us-east-1
tests:
  logging-top-level:
    regions:
      - us-east-1
    template: templates/deepwatch-root-stack.yaml
    parameters:
      pSRAStagingS3KeyPrefix: $[taskcat_project_name]
      pSRASourceS3BucketName: $[taskcat_autobucket]
      pSRASourceS3BucketNamePrefix: $[taskcat_project_name]
      pSRAS3BucketRegion: us-east-1
      pAutoEnableS3Logs: 'true'
      pAutoEnableK8sLogs: 'false'
      pAutoEnableMalwareProtection: 'false'
      pSRASolutionName: sra-guardduty-org
      pSraTestingFlag: 'true'
      pDeepwatchRoleName: 'deepwatch-mdr-role'
