project:
  name: cfn-abi-deepwatch-mdr
  owner: zachary.wallace@deepwatch.com
  package_lambda: false
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
  - us-east-1
tests:
  logging-top-level:
    regions:
      - us-east-1
    template: templates/deepwatch-root-stack.yaml
    parameters:
      pSRASourceS3BucketName: $[taskcat_autobucket]
      pSRAS3BucketRegion: us-east-1
      pAutoEnableS3Logs: 'true'
      pAutoEnableKubernetesAuditLogs: 'false'
      pAutoEnableMalwareProtection: 'false'
      pDeepwatchRoleName: 'deepwatch-mdr-role'
      pEnableLambdaDataEvents: 'false'
      pEnableS3DataEvents: 'true'
      pDisableGuardDuty: 'Yes'

  logging-top-level-defaults:
    regions:
      - us-east-1
    template: templates/deepwatch-root-stack.yaml
    parameters:
      pSRASourceS3BucketName: $[taskcat_autobucket]
      pDisableGuardDuty: 'Yes'