AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Configures services and resources for CloudTrail and GuardDuty logging in
  Deepwatch cloud MDR
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: General Properties
        Parameters:
          - pDeepwatchRoleName
      - Label:
          default: GuardDuty Configuration Properties
        Parameters:
          - pAutoEnableS3Logs
          - pAutoEnableK8sLogs
          - pAutoEnableMalwareProtection
      - Label:
          default: CloudTrail Configuration Properties
        Parameters:
          - pEnableLambdaDataEvents
          - pEnableS3DataEvents
    ParameterLabels:
      pAutoEnableS3Logs:
        default: Auto Enable S3 Logs
      pAutoEnableK8sLogs:
        default: Auto Enable kubernetes Logs
      pAutoEnableMalwareProtection:
        default: Auto Enable malware protection
      pDeepwatchRoleName:
        default: IAM Role name for Deepwatch solution access
      pEnableLambdaDataEvents:
        default: Enable Cloud Trail Data Events for all Lambda functions
      pEnableS3DataEvents:
        default: Enable Cloud Trail S3 Data Events for all buckets
Parameters:
  pAutoEnableS3Logs:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Auto enable S3 logs
    Type: String
  pAutoEnableK8sLogs:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Auto Enable kubernetes Logs
    Type: String
  pAutoEnableMalwareProtection:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Auto Enable malware protection
    Type: String
  pDeepwatchRoleName:
    AllowedPattern: '^([\w.-]{1,900})$|^(\/[\w.-]{1,900})*[\w.-]{1,900}$'
    ConstraintDescription: 'Must be alphanumeric or special characters [., _, -].'
    Default: deepwatch-mdr-role
    Description: The name of the role that will be created to provide access to ingest logs
    Type: String
  pEnableLambdaDataEvents:
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: Enable Cloud Trail Data Events for all Lambda functions
    Type: String
  pEnableS3DataEvents:
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: Enable Cloud Trail S3 Data Events for all buckets
    Type: String
Resources:
  CloudTrailStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub >-
        https://aws-abi-pilot.s3.us-east-1.${AWS::URLSuffix}/cfn-abi-deepwatch-mdr/submodules/cfn-abi-aws-cloudtrail/templates/sra-cloudtrail-enable-in-org-ssm.yaml
      Parameters:
        pEnableDataEventsOnly: false
        pEnableS3DataEvents: !Ref pEnableS3DataEvents
        pEnableLambdaDataEvents: !Ref pEnableLambdaDataEvents
  GuardDutyStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub >-
        https://aws-abi-pilot.s3.us-east-1.${AWS::URLSuffix}/cfn-abi-deepwatch-mdr/submodules/cfn-abi-amazon-guardduty/templates/sra-guardduty-enable-in-org-ssm.yaml
      Parameters:
        pAutoEnableS3Logs: !Ref pAutoEnableS3Logs
        pAutoEnableK8sLogs: !Ref pAutoEnableK8sLogs
        pAutoEnableMalwareProtection: !Ref pAutoEnableMalwareProtection
  DeepwatchResourceConfigurationStack:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: deepwatch-logging-resource-configuration
      AdministrationRoleARN: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/AWSControlTowerStackSetRole
      CallAs: SELF
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: Creates and configures all of the resources needed to begin ingestion of logs into Deepwatch MDR
      ExecutionRoleName: AWSControlTowerExecution
      ManagedExecution:
        Active: true
      OperationPreferences:
        FailureTolerancePercentage: 0
        MaxConcurrentPercentage: 100
        RegionConcurrencyType: PARALLEL
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !GetAtt [CloudTrailStack, Outputs.oLogArchiveAccountId]
          Regions:
            - !Ref AWS::Region
      TemplateURL: !Sub >-
        https://aws-abi-pilot.s3.us-east-1.${AWS::URLSuffix}/cfn-abi-deepwatch-mdr/templates/deepwatch-logging-resource-configuration.yaml
      Parameters:
        - ParameterKey: pGuardDutyBucketName
          ParameterValue: !GetAtt [GuardDutyStack, Outputs.oPublishingDestinationBucketName]
        - ParameterKey: pControlTowerBucketName
          ParameterValue: !GetAtt [CloudTrailStack, Outputs.oOrganizationCloudTrailS3BucketName]
        - ParameterKey: pDeepwatchRoleName
          ParameterValue: !Ref pDeepwatchRoleName
